# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Item.create([{name: 'flashlight'}, {name: 'axe'}, {name: 'bag'}, {name: 'painting'}, {name: 'head'}])


Story.create([
    { paragraph: 'You’ve woken up, alone and disoriented, in a pitch black room. As your eyes adjust to the darkness, you gradually recognize your bedroom. A harsh breeze cuts through the air, jolting your senses. As your thoughts begin to coalesce,  you hear a heavy rain and realize the single pane window to the left of your bed must have been blown open due to the storm. The bedroom is oppressively cold, and if there’s any chance you’re going to get more sleep, you’re going to have to close the window. '},
    { paragraph: 'You get up slowly, still slightly disoriented. The residual sleep fog clouds your head as you begin to find your balance. Pushing against the frigid breeze, you maneuver around violently flapping curtains to close the window. You hear it latch with a small ‘click’. With the window closed, you notice a small puddle has accumulated beneath the window, next to the lamp on your nightstand. There might be a rag you can use to wipe it up somewhere around here. The room is still too dark to see anything. You need to turn on the lamp.'},
    { paragraph: 'You get back in bed, but the room is freezing. There’s no way you’re going to be able to go back to sleep.'},
    { paragraph: 'You turn the small knob a few times. Nothing happens.    '},
    { paragraph: 'You stumble along the adjacent wall, feeling for the light switch as you walk. Eventually, you get close to the door and feel the switch on the wall.'},
    { paragraph: 'You flip the switch. Nothing happens. '},
    { paragraph: 'Nothing happens.'},
    { paragraph: 'After trying the light switch a few times, you realize the power must have gone out due to the storm. This is not unusual- your apartment building was built in the late 1800’s and hasn’t been well maintained. You’ve already begun adjusting to the darkness anyways, and the sun will begin to rise within the hour. You remember there is a flashlight in the nightstand.    '},
    { paragraph: 'You stumble back towards the nightstand and fumble open the top drawer. Inside, you find the flashlight and a couple bobby pins.'},
    { paragraph: 'You take the flashlight and exit your bedroom. You walk down the narrow L-shaped hallway which leads to your kitchen, passing by a restroom, a closet, and a small living room on your way. Nothing seems out of the ordinary. However, once you open the cabinet beneath the left side of the kitchen sink to get a rag, you can’t seem to find one. You usually have plenty of them. Where could they be? '},
    { paragraph: 'Within the right side of the cabinet sits a small trash bin with an item inside. It’s too dark to see inside the bin without removing it from the cabinet.'},
    { paragraph: 'Upon removing the bin from the cabinet, you find a small handaxe inside it. '},
    { paragraph: 'Surprised, you inspect the axe as closely as possible using your flashlight. It appears to have been cleaned recently. The blade, however, is rather dull- it looks like it’s been heavily used. It may not be as useful now as it was at another point in time.    '},
    { paragraph: 'You return the axe to the bin, and put the bin back in the cabinet. Still in the kitchen, you wonder where else you might find a rag. While you’re thinking, you start your morning routine. '},
    { paragraph: 'You turn on the stove, fill a slightly rusted red kettle with a few cups of water and place it on the lit burner. '},
    { paragraph: 'You then take a moment to fill your cat’s water bowl. It dawns on you that you haven’t seen Pluto yet this morning. You hope he didn’t escape through the open window.    '},
    { paragraph: 'You take a moment to fill your cat’s water bowl. It dawns on you that you haven’t seen Pluto yet this morning. You hope he didn’t escape through the open window.    '},
    { paragraph: 'You then turn on the stove, fill a slightly rusted red kettle with a few cups of water and place it on the lit burner. '},
    { paragraph: 'You take the axe. Still in the kitchen, you wonder where else you might find a rag. While you’re thinking, you start your morning routine. '},
    { paragraph: 'You turn on the stove, fill a slightly rusted red kettle with a few cups of water and place it on the lit burner. '},
    { paragraph: 'You then take a moment to fill your cat’s water bowl. It dawns on you that you haven’t seen Pluto yet this morning. You hope he didn’t escape through the open window.    '},
    { paragraph: 'You take a moment to fill your cat’s water bowl. It dawns on you that you haven’t seen Pluto yet this morning. You hope he didn’t escape through the open window.    '},
    { paragraph: 'You turn on the stove, fill a slightly rusted red kettle with a few cups of water and place it on the lit burner. '},    
    { paragraph: 'Pluto is nowhere to be found in the kitchen, so you go back out into the hallway. You walk in the direction of your bedroom in search of the cat, periodically calling his name.'},
    { paragraph: 'Your living room is sparsely furnished, being composed of a television atop an oak stand, an old couch, and a small coffee table. Two windows overlook a typically busy street, now empty in the early hours of the morning. A street lamp flickers, providing intermittent images of leaves, scattered on the road, now wet and slippery from the heavy rain.  Pluto, usually curled up on the far end of the sofa, is nowhere to be found.    '},
    { paragraph: 'Your bathroom is small and houses only the essentials - sink, toilet, shower, mirror. You notice a cardigan which doesn’t belong to you resting upon the towel bar on the wall. What visitor could have left it here by mistake? You leave the cardigan on the towel bar, deciding to deal with it later. Pluto is still not in sight.'},
    { paragraph: 'Your closet houses your three pairs of shoes, several jackets belonging to you, and various supplies such as paper towels and toilet tissue. Additionally, there are an extra two pairs of shoes, much smaller than yours and in a different style than your own, and a few jackets not belonging to you, also smaller and differently fashioned than yours. A black garbage bag is shoved into the back left corner of the closet floor. Pluto is still nowhere to be found.    '},
    { paragraph: 'Inside of the garbage bag  you find some small items: various trinkets, a framed photograph of yourself and a woman, and two gold rings in different sizes.     '},
    { paragraph: 'You enter your bedroom. Dawn is arriving slowly, and although it is still raining, small rays of orange light peak through the clouds. The light creeps its way through the trees and into the walls of your room. Suddenly, you hear the unmistakable cry of a cat, and as you do, the kettle begins to boil.        '},
    { paragraph: ' You head down the hallway towards the kitchen. The cat’s cries echo throughout the house from behind you, almost as if it were upset with you for choosing to return to the kitchen. As you enter the kitchen, steam billows out of the screeching kettle. You turn off the stove and search the nearest cabinet for your tea box. '},
    { paragraph: 'You set up a cup and saucer, and select your favorite black tea from the teabox. You notice there is a wider variety of tea in the box than you remember- why would there be Pu-Erh tea in the tea box when you decidedly do not like the stinky, smoky flavor of Pu-Erh tea?        '},
    { paragraph: 'Your attention must remain on the search for Pluto. As you return to your bedroom, sparse rays of the angry sun creep through the curtains and illuminate the framed painting on your wall. Contorting through the trees, shadows seem to taunt you as their twisted figures resemble a woman’s silhouette in front of the painting. At that instant, you hear Pluto cry out once more. Or was it the woman who was crying? No, no. It sounds almost as if Pluto were inside the painting itself. His cries are becoming more hysterical. The kettle too screams with urgency and forces you to direct your attention back to the kitchen.'},
    { paragraph: 'Your attention must remain on the search for Pluto. As you return to your bedroom, sparse rays of the angry sun creep through the curtains and illuminate the framed painting on your wall. Contorting through the trees, shadows seem to taunt you as their twisted figures resemble a woman’s silhouette in front of the painting. At that instant, you hear Pluto cry out once more. Or was it the woman who was crying? No, no. It sounds almost as if Pluto were inside the painting itself. The cries are becoming more hysterical.'},
    { paragraph: 'You quickly turn off the burner and return to the bedroom, leaving the kettle on the stove. Pluto’s hysterical cries are beginning to give you a headache. Where is he?'},
    { paragraph: 'Upon removing the painting from the wall, you can see that a portion of the wall was patched up, quite poorly, with putty. '},
    { paragraph: 'You search your bedroom again, to no avail. Pluto’s cries still sound like they’re coming from inside the painting.'},
    { paragraph: 'You reach out and tap the wall twice. Each tap is followed by a shallow echo. The wall is hollow. In reaction to the taps is the howl of a distraught cat, undoubtedly Pluto. How could he have gotten stuck in the wall? How can you get him out?'},
    { paragraph: 'You still have the axe that you picked up in the kitchen. The blade is dull, but still sharp enough to break through drywall.'},
    { paragraph: 'You remember the axe under the sink. You walk to the kitchen, ripping open the cabinet to grab the trash bin. You grab the axe, leaving the bin in the middle of the room.'},
    { paragraph: 'You approach the wall carefully. After you sturdy yourself, you’re ready to begin tearing down the wall.'},
    { paragraph: 'You swing at the wall, only creating a small hole.'},
    { paragraph: 'You swing at the wall again, this time making the hole a bit bigger.    '},
    { paragraph: 'The wall falls apart easily, chunks of damp putty scattering and covering your hands in dust. The hole reveals the top of Pluto’s ears. The cat hisses. He’s still stuck.'},
    { paragraph: 'You continue swinging at the wall, slowly making the hole bigger.'},
    { paragraph: 'The wall begins to crumble towards your feet. Pluto looks at you, still inside the wall, and only then can you see his face dripping with blood. How is this possible? There’s no way you could have hurt him while opening the wall. Could you have hit him accidentally? You begin to panic at the thought, scrambling to pull Pluto from the wall. The hole still isn’t big enough to pull him out. '},
    { paragraph: 'You continue smashing the wall for what feels like an eternity. Finally, the hole is big enough to pull Pluto out. '},
    { paragraph: 'You use your hands to pull apart chunks of the wall for what feels like an eternity. Finally, the hole is big enough to pull Pluto out.'},
    { paragraph: 'You reach into the wall to pick him up. With a feral look in his eye, he scratches your hand. Terrified you may have hurt him, you grab him by the scruff of the neck, and pull him out.  His claws are fully extended and holding onto something dark maroon: the kitchen rags, soaked in blood, tumble out with him.  Upon closer inspection, it becomes clear the blood soaking his fur and the rags doesn’t belong to him. He must have eaten a rodent- there are plenty of them living in the walls. You cradle Pluto for a moment, but he hisses at you and scratches your face. With his nails dug into your arm, he jumps from your embrace and runs off. You should probably remove whatever animal he managed to attack.'},
    { paragraph: 'You look into the wall with your flashlight and can clearly see there’s something in there, much bigger than the expected rodent.'},
    { paragraph: 'You reach into the hole and feel something fleshy and wet. You begin to dry heave as you feel matted, tangled fur, and what feels like bone. You pull your hand back in shock after feeling a pool of slime you can only assume to be blood.'},
    { paragraph: 'You regain your courage after taking a breath and reach in again, grabbing the creature by the fur. It is heavy, and something feels strange about its shape. You tug at it, and fearfully, but forcefully pull it towards the hole. After a minute or two of struggle, you manage to yank it half way through, falling backwards onto the ground. You look up and find it difficult to process what you are looking at.'},
    { paragraph: 'The mangled head of a woman is resting in the wall, as if in a stockade. Who is she? How did she get here? Though covered in blood and beginning to decay, she looks familiar. She’s the woman in the photo. A gash in her forehead resembles the size of your handaxe.'},
    { paragraph: 'This doesn’t make sense.'},
    { paragraph: 'This couldn’t have been your doing, you try to convince yourself, but it’s all coming back to you in violent bursts of memory. There’s no denying what has occurred.'},
    { paragraph: 'The hallway is dark. You call for Pluto, and again get no response.' },
    { paragraph: 'The hallway is dark. You call for Pluto, and again get no response.'},
    # { paragraph: ''},
])

Response.create([
    { nextparagraph: 2, response: 'Get up.', story_id: 1 },
    { nextparagraph: 3, response: 'Get back in bed.', story_id: 2 },
    { nextparagraph: 4, response: 'Turn on lamp.', story_id: 3 },
    { nextparagraph: 4, response: 'Turn on lamp.', story_id: 2 },
    { nextparagraph: 4, response: 'Try again.', story_id: 4 },
    { nextparagraph: 5, response: 'Look for light switch.', story_id: 4 },
    { nextparagraph: 6, response: 'Flip switch.', story_id: 5 },
    { nextparagraph: 7, response: 'Try again.', story_id: 6 },
    { nextparagraph: 8, response: 'Try again.', story_id: 7 },
    { nextparagraph: 9, response: 'Return to nightstand.', story_id: 8},
    { nextparagraph: 10, response: 'Take flashlight.', story_id: 9 },
    { nextparagraph: 11, response: 'Open adjacent cabinet.', story_id: 10},
    { nextparagraph: 12, response: 'Remove bin.', story_id: 11 },
    { nextparagraph: 13, response: 'Inspect axe.', story_id: 12 },
    { nextparagraph: 14, response: 'Return axe to bin.', story_id: 13 },
    { nextparagraph: 19, response: 'Take axe.', story_id: 13 },
    { nextparagraph: 15, response: 'Make tea.', story_id: 14},
    { nextparagraph: 17, response: 'Feed cat.', story_id: 14},
    { nextparagraph: 16, response: 'Feed cat.', story_id: 15},
    { nextparagraph: 24, response: 'Look for Pluto.', story_id: 16},
    { nextparagraph: 18, response: 'Make tea.', story_id: 17 },
    { nextparagraph: 24, response: 'Look for Pluto.', story_id: 17 },
    { nextparagraph: 20, response: 'Make tea.', story_id: 19 },
    { nextparagraph: 22, response: 'Feed cat.', story_id: 19 },
    { nextparagraph: 21, response: 'Feed cat.', story_id: 20 },
    { nextparagraph: 24, response: 'Look for Pluto.', story_id: 21 },
    { nextparagraph: 23, response: 'Make tea.', story_id: 22 },
    { nextparagraph: 24, response: 'Look for Pluto.', story_id: 23},
    { nextparagraph: 25, response: 'Search living room.', story_id: 24 },
    { nextparagraph: 26, response: 'Search bathroom.', story_id: 24 },
    { nextparagraph: 27, response: 'Search closet.', story_id: 24 },
    { nextparagraph: 55, response: 'Return to hallway.', story_id: 25 },
    { nextparagraph: 55, response: 'Return to hallway.', story_id: 26 },
    { nextparagraph: 55, response: 'Return to hallway.', story_id: 27 },
    { nextparagraph: 26, response: 'Search bathroom.', story_id: 55 },
    { nextparagraph: 27, response: 'Search closet.', story_id: 55 },
    { nextparagraph: 25, response: 'Search living room.', story_id: 55 },
    { nextparagraph: 28, response: 'Inspect bag.', story_id: 27 },
    { nextparagraph: 56, response: 'Return to hallway.', story_id: 28 },
    { nextparagraph: 30, response: 'Turn off the stove.', story_id: 29 },
    { nextparagraph: 32, response: 'Search for Pluto.', story_id: 29 },
    { nextparagraph: 31, response: 'Make tea.', story_id: 30 },
    { nextparagraph: 33, response: 'Continue searching for Pluto.', story_id: 31 },
    { nextparagraph: 34, response: 'Return to kitchen.', story_id:  32},
    { nextparagraph: 35, response: 'Remove painting.', story_id: 33 },
    { nextparagraph: 36, response: 'Search bedroom.', story_id:  34 },
    { nextparagraph: 35, response: 'Remove painting.', story_id:  36},
    { nextparagraph: 37, response: 'Inspect wall.', story_id: 35 },
    { nextparagraph: 29, response: 'Return to bedroom.', story_id: 56 },
    { nextparagraph: 25, response: 'Search living room.', story_id: 56  },
    { nextparagraph: 26, response: 'Search bathroom.', story_id: 56 },
    { nextparagraph: 27, response: 'Search closet.', story_id: 56 },
    { nextparagraph: 38, response: 'Use axe.', story_id: 37 },
    { nextparagraph: 40, response: 'Approach wall.', story_id: 38 },
    { nextparagraph: 41, response: 'Swing axe.', story_id: 40 },
    { nextparagraph: 42, response: 'Swing again.', story_id: 41 },
    { nextparagraph: 43, response: 'Swing again.', story_id: 42 },
    { nextparagraph: 44, response: 'Continue using axe.', story_id:  43 },
    { nextparagraph: 45, response: 'Swing again.', story_id: 44 },
    { nextparagraph: 46, response: 'Use axe.', story_id: 45 },
    { nextparagraph: 47, response: 'Use your hands.', story_id: 45 },
    { nextparagraph: 48, response: 'Grab Pluto.', story_id: 46 },
    { nextparagraph: 48, response: 'Grab Pluto.', story_id: 47 },
    { nextparagraph: 49, response: 'Inspect wall.', story_id: 48 },
    { nextparagraph: 50, response: 'Reach into wall.', story_id: 49 },
    { nextparagraph: 51, response: 'Take item from wall.', story_id: 50 },
    { nextparagraph: 52, response: 'Inspect item.', story_id: 51 },
    { nextparagraph: 53, response: `What's going on?` , story_id: 52 },
    { nextparagraph: 54, response: `How could this have happened?`, story_id:  53},
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
    { nextparagraph: , response: '', story_id:  },
])